### ISSUE TITLE
Allow disabling of Installation notice

### ISSUE THREAD

**Issue by tott** [10up/wp-newrelic#14]
In some cases NewRelic APM is not installed on all available servers due to the cost impact. In this cases the installation notice that is fired when the NewRelic extension is not installed can be troublesome.  The following code change can provide a work-around.

	diff --git a/classes/class-wp-nr.php b/classes/class-wp-nr.php
	index ec454ea..b99d343 100644
	--- a/classes/class-wp-nr.php
	+++ b/classes/class-wp-nr.php
	@@ -13,6 +13,11 @@ class WP_NR {
	                        $this->include_files();
	                        $this->init();
	                } else {
	+                       // enable a bypass for installations where you might want to install the plugin only on a specified set of servers
	+                       if ( defined( 'WP_NR_DISABLE_INSTALL_NOTICE' ) && true === WP_NR_DISABLE_INSTALL_NOTICE ) {
	+                               return;
	+                       }
	+
	                        if ( WP_NR_IS_NETWORK_ACTIVE ) {
	                                add_action( 'network_admin_notices', array( $this, 'wp_nr_not_installed_notice' ) );
	                        } else {

**Comment by allan23** [comment]
PR merged.
