### ISSUE TITLE
Move New Relic menu item into settings

### ISSUE THREAD

**Issue by TheLastCicada** [10up/wp-newrelic#2]
Doesn't feel to me that New Relic should be a top level nav item in the wp-admin.  This feels much more appropriate to have in the Settings menu.  

Open for discussion if people feel differently.  
![screenshot 2016-12-05 14 54 16](https://cloud.githubusercontent.com/assets/3232332/20906017/0890d192-bafb-11e6-8cf4-373b5f64a1b3.png)

**Comment by Ritesh-patel** [comment]
Instead of top level menu we can also make that sub menu under "Settings".

**Comment by tott** [comment]
Let's do a sub menu in Tools. This seems more appropriate to me

**Comment by Ritesh-patel** [comment]
Settings page added as a sub menu in Tools.

**Comment by Ritesh-patel** [comment]
Update: if plugin is network active in WPMU setup, it will be main menu item.
