### ISSUE TITLE
Rest Requests never show up

### ISSUE THREAD

**Issue by Rahe** [10up/wp-newrelic#20]
Hello,

I have noticed that the action "wp" isn't launched on REST requests so no "REST API" traces are logged into New Relic.
I have fixed this with this code 
```php
                if ( is_admin() ) {
                        add_action( 'admin_init', array( $this, 'set_admin_transaction' ) );
                } else {
                        add_action( 'wp', array( $this, 'set_wp_transaction' ) );
                        add_action( 'rest_api_init', array( $this, 'set_wp_transaction' ) );
                }
```

Maybe there is a better way to do this ?

Cheers
Nicolas,

**Comment by brandwaffle** [comment]
@Rahe that looks like a good solution to me! Can you submit a pull request and I'll merge? Thanks for reporting!

**Comment by Rahe** [comment]
Hello,

Here it is https://github.com/10up/wp-newrelic/pull/21 :)

**Comment by brandwaffle** [comment]
Awesome, thank you! PR is merged!

**Comment by Rahe** [comment]
This is great, thank you for the reactivity :)
