### ISSUE TITLE
Incompatibility /w Multisite & Beaver Builder

### ISSUE THREAD

**Issue by raptor235** [10up/wp-newrelic#25]
We had installed this for a client a few weeks ago and it's caused us good 8 hours of research as to why administrators on some pages would get denied access to edit Beaver Builder pages... 

It seems that by running 
```
newrelic_set_user_attributes( $user->ID, '', array_shift( $user->roles ) );
```

You guys are unsetting user roles for that particular user... users administrator roles were being removed... after disabling that line in class-wp-nr-apm.php functionality to BB has returned to normal... 

Not a great way to spend 8 hours of company time trying to track this down today :(

**Comment by oscarssanchez** [comment]
HI @raptor235 , thanks for raising this issue!

It seems that by using array_shift to retreive the current user role, the role property ends up null if the user does not have any other roles. Using other method to retrieve the first key of the property would solve this issue. I'll try to come up with a PR.

**Comment by oscarssanchez** [comment]
Hi @raptor235 , does  https://github.com/10up/wp-newrelic/pull/27 works for you?
