### ISSUE TITLE
Add context for "Capture URLs"

### ISSUE THREAD

**Issue by TheLastCicada** [10up/wp-newrelic#3]
There's 1 checkbox in the settings for this plugin.  I have no idea what "capture URLs" means.  I'd be more user-friendly to add some explanation for what this checkbox is doing.  

![screenshot 2016-12-05 14 54 16](https://cloud.githubusercontent.com/assets/3232332/20906062/3418f916-bafb-11e6-93d9-f9a7b68d4699.png)

**Comment by Ritesh-patel** [comment]
Yes, you are right, there should be a description message. I have added "Enable this to record parameter passed to PHP script via the URL (everything after the "?" in the URL).".

**Comment by tott** [comment]
This should then also be renamed to "Capture URL parameters" I think

**Comment by Ritesh-patel** [comment]
Label updated.
