### ISSUE TITLE
WP New Relic: New Relic is not installed. error is showing

### ISSUE THREAD

**Issue by lukecav** [10up/wp-newrelic#39]
New Relic Reporting for WordPress plugin is installed and active but is being reported that is it not.

**Comment by lukecav** [comment]
`
### WordPress Environment ###

WordPress address (URL): https://cannanine.com
Site address (URL): https://cannanine.com
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.12.1
PHP Version: 7.3.3-1+ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 200 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.43-84.3
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
Total Database Size: 1255.76MB
Database Data Size: 475.77MB
Database Index Size: 779.99MB
wp_woocommerce_sessions: Data: 18.05MB + Index: 2.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 17.55MB + Index: 7.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 107.66MB + Index: 100.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.17MB + Index: 0.27MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.25MB + Index: 0.25MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tempMailerCustomers: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
tmpAutoshipCBDOilCustomers20190322: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpMailerCustomersExistingCustomers: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
tmpMailerSalesToDate: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
tmpOnHoldCBDOilCustomers20190320: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ap_csv_export_data: Data: 9.52MB + Index: 4.03MB + Engine InnoDB
wp_bs_donation_purpose: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bs_donation_report: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_bs_dropshipping_clarification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bs_feed_shelterdogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bs_feed_shelterdogs_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bs_other_donation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bs_other_donation_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_comments: Data: 46.58MB + Index: 33.06MB + Engine InnoDB
wp_cpf_custom_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cp_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_order_feedback_dropshipper_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_order_feedback_emails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_cy_order_feedback_email_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_order_feedback_product_ratings: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_cy_popup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ir_wc_tracking_emails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_litespeed_optimizer: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.22MB + Index: 0.19MB + Engine InnoDB
wp_postmeta: Data: 203.75MB + Index: 586.31MB + Engine InnoDB
wp_posts: Data: 30.47MB + Index: 23.91MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_taxjar_record_queue: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.25MB + Index: 0.45MB + Engine InnoDB
wp_term_relationships: Data: 0.41MB + Index: 0.44MB + Engine InnoDB
wp_term_taxonomy: Data: 0.27MB + Index: 0.75MB + Engine InnoDB
wp_usermeta: Data: 17.36MB + Index: 13.98MB + Engine InnoDB
wp_users: Data: 0.48MB + Index: 0.42MB + Engine InnoDB
wp_wc_autoship_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_autoship_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wc_autoship_schedules: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_autoship_schedule_items: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.45MB + Index: 0.11MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.14MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

AP CSV Exporter: by Ananta Pattanayak – 0.1.0
Autoship Cloud powered by QPilot: by Patterns In the Cloud LLC – 1.2.46 – Not tested with the active version of WooCommerce
Autoship Cloud Solutions - Dynamic Pricing Extension: by Patterns In the Cloud LLC – 1.1.2 – Not tested with the active version of WooCommerce
Autoship Cloud Solutions - Utilities Extension: by Patterns In the Cloud LLC – 1.0.0 – Not tested with the active version of WooCommerce
Dropshipping Clarification: by Bibhakar Sarkar (Bibhu) – 1.1
BS Feed Shelter Dogs: by Bibhakar Sarkar (Bibhu) – 1.0
Classic Editor: by WordPress Contributors – 1.5
CY Order Feedback Email: by Ananta Pattanayak – 1.0
Disable Cart Fragments: by LittleBizzy – 1.3.0 – Not tested with the active version of WooCommerce
GP Premium: by Tom Usborne – 1.9.1
Heartbeat Control by WP Rocket: by WP Rocket – 2.0
Iconic Sales Booster for WooCommerce: by Iconic – 1.1.2 – Not tested with the active version of WooCommerce
WooCommerce Gift Certificates Pro: by IgniteWoo.com – 3.5.36 – Not tested with the active version of WooCommerce
Woocommerce Item Add To Cart Plugin: by Ivan Rodriguez – 4.0 – Not tested with the active version of WooCommerce
HLM Woocommerce Conversion Tags: by Ivan Rodriguez – 2.2 – Not tested with the active version of WooCommerce
Woocommerce Customer Service Lookup: by Ivan Rodriguez – 1.0.4 – Not tested with the active version of WooCommerce
Woocommerce Free Shipping Offer: by Ivan Rodriguez – 1.0 – Not tested with the active version of WooCommerce
Woocommerce Reports for HLM: by Ivan Rodriguez – 1.0 – Not tested with the active version of WooCommerce
Woocommerce Tracking Number Email Plugin: by Ivan Rodriguez – 1.3 – Not tested with the active version of WooCommerce
iThemes Sync: by iThemes – 2.1.0
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.5
LiteSpeed Cache: by LiteSpeed Technologies – 2.9.9.2
Members: by Justin Tadlock – 2.2.0
Metorik Helper: by Metorik – 1.3.0 – Not tested with the active version of WooCommerce
Smart Slider 3 Pro: by Nextend – 3.3.24
OptinMonster API: by OptinMonster Team – 1.9.6
Redirection: by John Godley – 4.5.1
Scripts-To-Footer: by Joshua David Nelson – 0.6.3
SendGrid: by SendGrid – 1.11.8
Smart Offers: by StoreApps – 3.10.3 – Not tested with the active version of WooCommerce
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.22
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.0.11 – Not tested with the active version of WooCommerce
Ultimate FAQ: by Etoile Web Design – 1.8.29 – Not tested with the active version of WooCommerce
User Switching: by John Blackbourn & contributors – 1.5.3
WooCommerce Order Search Admin powered by Algolia: by Raymond Rutjes – 1.12.1 – Not tested with the active version of WooCommerce
WooCommerce Cost of Goods: by SkyVerge – 2.9.2 – Not tested with the active version of WooCommerce
WooCommerce Custom Popularity Orderby: by HomeLife Media – 2.0.0 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.15 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.15 – Not tested with the active version of WooCommerce
Klaviyo for WooCommerce V2: by Klaviyo
Inc. – 2.0.0 – Not tested with the active version of WooCommerce

WooCommerce - ShipStation Integration: by WooCommerce – 4.1.30 – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 2.0.8 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.18 – Not tested with the active version of WooCommerce
WooCommerce Waitlist: by WooCommerce – 2.1.12 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.0 – 3.8.1 is available
Yoast SEO Premium: by Team Yoast – 12.7.1
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
New Relic Reporting for WordPress: by 10up – 1.3
WP-Paginate: by Max Foundry – 2.0.6
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.1
Widget Disable: by required – 1.9.1

### Inactive Plugins (7) ###

AP Gift Message: by Ananta Pattanayak – 0.1.0
Compress JPEG & PNG images: by TinyPNG – 3.2.1
PayPal for WooCommerce: by Angell EYE – 1.5.7 – Not tested with the active version of WooCommerce
Two Factor: by Plugin Contributors – 0.4.7
WooCommerce - Custom Orders Table: by Liquid Web – 1.0.0-rc3 – Not tested with the active version of WooCommerce
WP Disable: by optimisation.io - jody nesbitt – 1.5.21
WP Maintenance Mode: by Designmodo – 2.2.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Jetpack Integration: by Liquid Web – 0.1.0
Liquid Web Managed WordPress: by Liquid Web <support@liquidweb.com> – 1.4
Liquid Web Managed WordPress Configuration: by Liquid Web – 1.0.0
Liquid Web Managed WordPress Platform Manager: by Liquid Web – 1.1.0
Liquid Web Update Manager: by Liquid Web <support@liquidweb.com> – 1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: GeneratePress Child
Version: 0.1
Author URL: https://tomusborne.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 2.4.1
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: generatepress_child/woocommerce/cart/cart.php
generatepress_child/woocommerce/checkout/form-shipping.php
generatepress_child/woocommerce/checkout/review-order.php
generatepress_child/woocommerce/checkout/thankyou.php
generatepress_child/woocommerce/content-product.php
generatepress_child/woocommerce/content-product_cat.php
generatepress_child/woocommerce/content-single-product.php
generatepress_child/woocommerce/content-widget-product.php
generatepress_child/woocommerce/emails/customer-note.php
generatepress_child/woocommerce/emails/customer-processing-order.php
generatepress_child/woocommerce/loop/add-to-cart.php
generatepress_child/woocommerce/loop/loop-end.php
generatepress_child/woocommerce/loop/loop-start.php
generatepress_child/woocommerce/loop/no-products-found.php
generatepress_child/woocommerce/loop/orderby.php
generatepress_child/woocommerce/loop/pagination.php
generatepress_child/woocommerce/loop/price.php
generatepress_child/woocommerce/loop/result-count.php
generatepress_child/woocommerce/loop/sale-flash.php
generatepress_child/woocommerce/order/order-details.php
generatepress_child/woocommerce/single-product/meta.php
generatepress_child/woocommerce/single-product/related.php
generatepress_child/woocommerce/single-product.php


### Square ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off

### Action Scheduler ###

Complete: 726
Oldest: 2019-11-17 16:55:04 -0800
Newest: 2019-12-18 13:55:05 -0800

Pending: 1
Oldest: 2019-12-20 15:18:03 -0800
Newest: 2019-12-20 15:18:03 -0800

Canceled: 2
Oldest: 2019-11-27 13:55:05 -0800
Newest: 2019-11-27 13:55:06 -0800

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by jeffpaul** [comment]
@lukecav was the plugin working previously?  If so, any idea what's changed recently that may have contributed to this issue (I'm considering WP 5.3, but wanted to get your input)?

**Comment by brandwaffle** [comment]
@lukecav when you say the plugin is installed do you mean the WP New Relic plugin is installed, or have you confirmed that the New Relic APM agent is running on the server? The error which indicates New Relic is not installed is looking for the APM Agent rather than the plugin itself.

**Comment by irodriguez777** [comment]
We recently updated to WP 5.3.1 and to PHP 7.3.3. The plugin was working correctly prior to the updates.

The WP New Relic plugin shows as being activated in the Plugins menu. Currently though, there is no data being passed to APM for this site.

**Comment by lukecav** [comment]
@jeffpaul 

Correct New Relic APM was working correctly before and the plugin did not display the error message.

**Comment by bswatson** [comment]
@brandwaffle @jeffpaul 

We're using the version available from the WP.org repo which does not appear to have been updated in over a year. Is there a plan to push out an update in the near future or should we switch to using the latest available from this repo?

**Comment by lukecav** [comment]
Same issue when using the dev branch on the site.

https://github.com/10up/wp-newrelic/archive/develop.zip

**Comment by jeffpaul** [comment]
@bswatson we do have a minor release planned, but per @lukecav's note it sounds like it doesn't resolve this issue (which makes sense as we weren't aware of the issue as we were working on bundling the release).  If someone is able to help dig into changes in core since 5.3 to see what might be causing this conflict, I'd happily get it through review and into a minor release to resolve this.

Note that we'll be out of the office from end of Friday, December 20th (today) through Wednesday, January 1st so it's unlikely that we'll ship a release to resolve this until early January at the earliest.

**Comment by jeffpaul** [comment]
It also sounds like most of the folks here are on PHP 7.3.*, but it may be easier if someone can downgrade their WP version to see if things return to normal pre-WP 5.3 and help us lock in which WP release is causing this (if it is a core-related issue at all).

**Comment by lukecav** [comment]
@jeffpaul 

I can test previous WordPress core versions to find out which version is causing the current issue.

**Comment by lukecav** [comment]
When testing on a new install site with only these plugins active;
**Classic Editor
New Relic Reporting for WordPress
WooCommerce**

PHP version
**php_version: 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 64bit**

The issue does not happen on any of the releases in the 5.3 branch
**5.3.2
5.3.1
5.3**

**Comment by lukecav** [comment]
### wp-core ###

version: 5.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/s1491/html
wordpress_size: 37.77 MB (39605369 bytes)
uploads_path: /home/s1491/html/wp-content/uploads
uploads_size: 7.10 MB (7447310 bytes)
themes_path: /home/s1491/html/wp-content/themes
themes_size: 4.63 MB (4859674 bytes)
plugins_path: /home/s1491/html/wp-content/plugins
plugins_size: 39.57 MB (41491390 bytes)
database_size: 3.13 MB (3276800 bytes)
total_size: 92.20 MB (96680543 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, woocommerce, post-thumbnails, automatic-feed-links, custom-background, custom-logo, title-tag, html5, align-wide, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: /home/s1491/html/wp-content/themes/twentytwenty

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-mu-plugins (4) ###

Liquid Web Managed WordPress: version: 1.4, author: Liquid Web <support@liquidweb.com>
Liquid Web Managed WordPress Configuration: version: 1.0.0, author: Liquid Web
Liquid Web Managed WordPress Platform Manager: version: 1.1.0, author: Liquid Web
Liquid Web Update Manager: version: 1.0, author: Liquid Web <support@liquidweb.com>

### wp-plugins-active (3) ###

Classic Editor: version: 1.5, author: WordPress Contributors
New Relic Reporting for WordPress: version: 1.3, author: 10up
WooCommerce: version: 3.8.1, author: Automattic

### wp-plugins-inactive (8) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic
Async JavaScript: version: 2.19.07.14, author: Frank Goossens (futtta)
Autoptimize: version: 2.5.1, author: Frank Goossens (futtta)
Beaver Builder Plugin (Lite Version): version: 2.2.6.3, author: The Beaver Builder Team
BJ Lazy Load: version: 1.0.9, author: Bjørn Johansen, Aron Tornberg, angrycreative
Compress JPEG & PNG images: version: 3.2.1, author: TinyPNG
Lazy Load for Comments: version: 1.0.10, author: Joel James
WPMerge: version: 1.2.6, author: Revmakx

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 7 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 7 GB
	imagick::RESOURCETYPE_MEMORY: 4 GB
	imagick::RESOURCETYPE_THREAD: 4
gd_version: 2.2.5
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.15.0-55-generic x86_64
httpd_software: nginx/1.14.0
php_version: 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 300
memory_limit: 256M
max_input_time: 60
upload_max_size: 200M
php_post_max_size: 200M
curl_version: 7.58.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 5.6.46-86.2
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/s1491/html/wp-content
WP_PLUGIN_DIR: /home/s1491/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

**Comment by jeffpaul** [comment]
@lukecav based on your results from https://github.com/10up/wp-newrelic/issues/39#issuecomment-567235496 (where things do NOT work) and https://github.com/10up/wp-newrelic/issues/39#issuecomment-568538815 / https://github.com/10up/wp-newrelic/issues/39#issuecomment-568538959 (where things DO work) it looks like the main difference is the PHP version changing from 7.3.3-1+ubuntu14.04.1+deb.sury.org+1 to 7.3.11-1+ubuntu18.04.1+deb.sury.org+1.  Would you please confirm that's the difference you're seeing as well?  If so, I'll look to update our documentation to note a conflict with PHP 7.3.3 and that updating to PHP 7.3.11 _should_ resolve things... thanks!

**Comment by michaelbourne** [comment]
I'm seeing this same admin notice on all sites I've installed the helper plugin on. All sites have the same server specs:

```Server architecture | Linux 4.15.0-196-generic x86_64
Web server | nginx/1.16.1
PHP version | 7.4.33 (Supports 64bit values)
PHP SAPI | fpm-fcgi
PHP max input variables | 5000
PHP time limit | 300
PHP memory limit | 256M
Max input time | 60
Upload max filesize | 512M
PHP post max size | 512M
cURL version | 7.58.0 OpenSSL/1.1.1
Is SUHOSIN installed? | No
Is the Imagick library available? | Yes
Are pretty permalinks supported? | Yes
```

Running `php -m` from the command line shows that `newrelic` is active. 

I know you're using `extension_loaded` to detect newrelic, so I'm not sure why it's not working.

I'll continue testing, but if you had any ideas why PHP can't detect the module but CLI can, I'm all ears.
