### ISSUE TITLE
Too many metric names being created

### ISSUE THREAD

**Issue by jasondewitt** [10up/wp-newrelic#4]
I installed this plugin on a client site last week and all was looking good. But over the weekend New Relic opened a ticket saying "This ticket was created due to a very large number of metric names being created for your php application"

It appears that a distinct transation type is being created for each custom post type, tag, category and page. 183 were created before New Relic stopped allowing new metric creation on this application.

**Comment by jasondewitt** [comment]
Here's some more info I go from NewRelic on the ticket

Thanks for following up. It looks like the plugin that you mentioned may actually be the root cause of the problem. The plugin looks to use the newrelic_name_transaction() API call to name transactions. This has created a large number of metrics that the system is not able to group properly. These include:
```
Apdex/Custom/Category - eagles-injury-report/page/*/www.phillymag.com/birds247/*/*/*/eagles-giants-injury-report
Apdex/Custom/Category - eagles-injury-report/page/*/www.phillymag.com/birds247/*/*/*/eagles-giants-injury-report-2
Apdex/Custom/Category - featured/page/*/www.phillymag.com/birds247/*/*/*/22-double-posts-red-zone
Apdex/Custom/Category - featured/page/*/www.phillymag.com/birds247/*/*/*/22-state-eagles-offense-2
Apdex/Custom/Page - Foobooz.com
Apdex/Custom/Page - Like%20PW%20on%20Facebook%20|%20Follow%20PW%20on%20Twitter%20|%20Sign%20up%20for%20the%20PW%20newsletter%20Read%20more%20at%20http:/www.phillymag.com/philadelphia-wedding/*/*/*/video-super-cute-flash-mob-proposal-south-street-festival-
```
It looks like the plugin is used to send up a description of each individual page, rather than generalizing them as overall transactions. This makes it more difficult for the system to display performance data trends, as while the underlying code for each of these pages may largely be the same, the transactions are differently named, causing the system to show these transactions disparately.

Ideally, the controller/action style naming scheme is recommended for most frameworks to identify transactions and code paths.

Let me know if that helps clear things up regarding what's going on.

**Comment by brandwaffle** [comment]
@jasondewitt can you follow up on the ticket with New Relic to confirm this only applies to the Transaction name (we can continue to log custom parameters that correspond to post IDs, for example).

We're looking into how the Category name could even be the way that it is now. It seems there's some tag duplication and the entire string is way longer than it should be. The code is just outputting the category name, so I wonder if this is somehow the result of multiple categories running over each other.

**Comment by jasondewitt** [comment]
I asked the question, we'll see what the answer is.

It's definitely something with how this particular site is set up. This is a multisite install, and the other three sites on the MU aren't having this issue.

**Comment by jasondewitt** [comment]
got a response back from NR, he said...aaaand I quote
```
 the metrics that we're seeing that cause this issue are just transactions, meaning anything created by the newrelic_name_transaction() API call.
```
