### ISSUE TITLE
Test against WordPress 5.5

### ISSUE THREAD

**Issue by jeffpaul** [10up/wp-newrelic#44]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.5 is released, we'll want to test WP New Relic to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test WP New Relic on WordPress 5.5
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by lukecav** [comment]
I have tested using the current version of the WP New Relic plugin on WordPress 5.5 and 5.5.1 and it is working correctly.

**Comment by jeffpaul** [comment]
Awesome, thanks @lukecav!  I'll push an update to the `tested up to` version then.
