### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by jeffpaul** [10up/wp-newrelic#46]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 6.0 RC1 is released, we'll want to test WP New Relic to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [ ] test WP New Relic on WordPress 6.0 RC1
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related: #44.

**Comment by Josecarpeniet** [comment]
Hello, this is not working anymore. I have WP 5.8 and the tool doesn't show on the menu "tools", so it is not possible to set it up.
It would be fantastic if you can fix it because it seems to be a really useful plugin.
Thanks

**Comment by tkyser-rodeo** [comment]
Are there any plans to update this?

**Comment by jeffpaul** [comment]
@tkyser-rodeo yes, though we have a some other releases ahead of this item.  If you're able to help with identifying where things are incompatible with WordPress core or even craft a PR to update, then that will speed this work along.

**Comment by ciprianimike** [comment]
I tested the plugin on WP v5.7.4, v5.8.1 with single and multisite installations.
All the tests seem to be passed without problems, but the problem marked with the menu must be investigated.

The menu works as aspected:
Single site: /wp-admin/tools.php?page=wp-nr-settings
Multisite: /wp-admin/network/admin.php?page=wp-nr-settings

@tkyser-rodeo @Josecarpeniet can you provide details on how to replicate your issue?

**Comment by jeffpaul** [comment]
@tkyser-rodeo @Josecarpeniet can you please provide additional details on reproducing your issues so that we can attempt to triage and resolve them?  Thanks!

**Comment by jeffpaul** [comment]
Note that I've updated this to now relate to WP 5.9 since 5.9 RC1 is available.
cc: @sudip-10up

**Comment by oscarssanchez** [comment]
Hi @Josecarpeniet this is likely because you don't have the extension. If you don't have the extension then it is expected this menu will not be shown. See: https://github.com/10up/wp-newrelic/blob/develop/classes/class-wp-nr.php#L14
