### ISSUE TITLE
 WordFence flags this plugin not being updated past 2 years?

### ISSUE THREAD

**Issue by jenfloods** [10up/wp-newrelic#48]
### Describe the bug

This is a concern using this plugin, will this be updated soon?

### Steps to Reproduce

Checking on if you are planning to make updates

### Environment information

Wordpress

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
Hi @jenfloods ,

Have you identified an incompatibility/bug with the plugin ?

If you can help us with testing the plugin with 5.9 (see: https://github.com/10up/wp-newrelic/issues/46#issuecomment-956698926) that would be great, and you happen to identify an issue, please feel free to open an issue in the repo, or create a PR as they are always welcomed.
