### ISSUE TITLE
Small typo in description {browse|d}

### ISSUE THREAD

**Issue by jgraup** [10up/wp-newrelic#5]
Looking at the [description](https://github.com/10up/wp-newrelic/blob/master/readme.txt#L20) from `/wp-admin/network/plugins.php` on a multisite environment, I am seeing a word that may be used incorrectly.

 
> Admin settings can be __browse__ after activating plugin. You should see a new option named New Relic under Tools menu. In case of WPMU, it could be found in network dashboard.
 

This seems to make more sense written as:

> Admin settings can be __browsed__ after activating plugin. You should see a new option named New Relic under Tools menu. In case of WPMU, it could be found in network dashboard.

**Comment by brandwaffle** [comment]
Thanks @jgraup. Updated the text to match the README.md file.
