### ISSUE TITLE
wp new relic: new relic is not installed.

### ISSUE THREAD

**Issue by Shereef** [10up/wp-newrelic#62]
### Describe your question

PHP 8.2 and the latest wordpress 6.4.1

When I go to tools it says `new relic is not installed.`

Any advice ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchezz** [comment]
Hi @Shereef ,

I just tried this myself, with the following software:

WordPress:  6.5.2
NewRelic: newrelic-php5-10.19.0.9-linux
PHP: 8.2.13
wp-newrelic: develop branch

The extension is picked up by the plugin without any issues.

My suggestion is to check your NewRelic installation. I used the following guide to install newrelic locally https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-tar-file/
