### ISSUE TITLE
"Disable for AMP" is an unnecessary option

### ISSUE THREAD

**Issue by goldenapples** [10up/wp-newrelic#7]
From a usability standpoint, having a "Disable for AMP" checkbox option in this plugin's settings is meaningless. Injecting the New Relic scripts into AMP pages will always break AMP validation and will not work for monitoring those pages, so you would never want to uncheck that box.

I'd recommend removing that option field and always disabling NR scripts for AMP pages.

**Comment by brandwaffle** [comment]
@goldenapples makes perfect sense, let's do it!
